WITH SOURCE AS (
    SELECT * FROM {{ source('src', 'lineitems') }}
),
LINEITEMS AS (
    SELECT
        L_ORDERKEY AS ORDER_ID,
        L_PARTKEY AS PART_ID,
        L_SUPPKEY AS SUPP_ID,
        L_LINENUMBER AS LINEITEM_ID,
        L_QUANTITY AS QUANTITY,
        L_EXTENDEDPRICE AS EXTENDED_PRICE,
        L_DISCOUNT AS DISCOUNT,
        L_TAX AS TAX,
        L_RETURNFLAG AS RETURN_FLAG,
        L_LINESTATUS AS LINE_STATUS,
        L_SHIPDATE AS SHIP_DATE,
        L_COMMITDATE AS COMMIT_DATE,
        L_RECEIPTDATE AS RECEIPT_DATE,
        L_SHIPINSTRUCT AS SHIP_INSTRUCT,
        L_SHIPMODE AS SHIP_MODE,
        L_COMMENT AS COMMENT
    FROM 
        SOURCE
)

SELECT * FROM LINEITEMS